'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';
import NavBar from '@/components/NavBar';

export default function FeedPage() {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const { user } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push('/login');
    }
  }, [user, router]);

  const fetchFeed = async (pageNum, append = false) => {
    try {
      if (append) {
        setLoadingMore(true);
      } else {
        setLoading(true);
      }
      setError('');

      const response = await fetch(`/api/feed?page=${pageNum}&limit=12`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to fetch feed');
      }

      if (append) {
        setImages((prev) => [...prev, ...data.images]);
      } else {
        setImages(data.images);
      }

      setTotalPages(data.totalPages);
      setTotal(data.total);
      setPage(data.page);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  };

  useEffect(() => {
    if (user) {
      fetchFeed(1);
    }
  }, [user]);

  const handleLoadMore = () => {
    if (page < totalPages) {
      fetchFeed(page + 1, true);
    }
  };

  const handleHeart = async (imageId, currentHearts) => {
    const newHearts = currentHearts + 1;

    // Optimistic UI update
    setImages((prev) =>
      prev.map((img) =>
        img.id === imageId ? { ...img, hearts: newHearts } : img
      )
    );

    try {
      const response = await fetch('/api/feed', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          id: imageId,
          hearts: newHearts,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to update hearts');
      }

      // Update with server response to ensure consistency
      setImages((prev) =>
        prev.map((img) => (img.id === imageId ? data : img))
      );
    } catch (err) {
      // Revert optimistic update on error
      setImages((prev) =>
        prev.map((img) =>
          img.id === imageId ? { ...img, hearts: currentHearts } : img
        )
      );
      console.error('Error updating hearts:', err);
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  if (!user || (loading && images.length === 0)) {
    return null;
  }

  return (
    <>
      <NavBar />
      <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="mb-8">
            <div className="flex justify-between items-center mb-4">
              <div>
                <h1 className="text-4xl font-bold text-gray-900 mb-2">
                  Image Gallery
                </h1>
                <p className="text-gray-600 mb-4">
                  {total} {total === 1 ? 'image' : 'images'} generated by the community
                </p>
              </div>
            </div>
            <Link
              href="/"
              className="inline-block text-blue-600 hover:text-blue-800 font-medium"
            >
              ← Generate New Image
            </Link>
          </div>

          {error && (
            <div className="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-lg mb-8 max-w-2xl mx-auto">
              <p className="font-medium">Error</p>
              <p className="text-sm">{error}</p>
            </div>
          )}

          {images.length === 0 && !loading ? (
            <div className="text-center py-20">
              <div className="text-gray-600 text-lg mb-4">
                No images yet. Be the first to create one!
              </div>
              <Link
                href="/"
                className="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors"
              >
                Generate Image
              </Link>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
                {images.map((image) => (
                  <div
                    key={image.id}
                    className="bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow"
                  >
                    <div className="aspect-square relative bg-gray-100">
                      <img
                        src={image.imageUrl}
                        alt={image.prompt}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="p-4">
                      <p className="text-gray-900 text-sm mb-3 line-clamp-2">
                        {image.prompt}
                      </p>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4">
                          <button
                            onClick={() => handleHeart(image.id, image.hearts)}
                            className="flex items-center gap-1 text-red-500 hover:text-red-600 transition-colors group"
                          >
                            <svg
                              className="w-5 h-5 group-hover:scale-110 transition-transform"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <span className="font-medium">{image.hearts}</span>
                          </button>
                          <div className="text-gray-500 text-sm">
                            {formatDate(image.createdAt)}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {page < totalPages && (
                <div className="text-center">
                  <button
                    onClick={handleLoadMore}
                    disabled={loadingMore}
                    className="bg-blue-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
                  >
                    {loadingMore ? 'Loading...' : 'Load More'}
                  </button>
                  <p className="text-gray-600 text-sm mt-3">
                    Showing {images.length} of {total}
                  </p>
                </div>
              )}

              {page >= totalPages && images.length > 0 && (
                <div className="text-center text-gray-600">
                  <p>You've reached the end of the gallery</p>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
}
